sudo: false

addons:
  apt:
    packages:
      - tidy

install: travis_retry bundle install --without=benchmark

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - rbx-2

matrix:
  allow_failures:
    - rvm: rbx-2

notifications:
  email: false
